// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: connections.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countConnectionRequestsToday = `-- name: CountConnectionRequestsToday :one
SELECT COUNT(*) FROM connections
WHERE requester_id = $1
AND created_at > NOW() - INTERVAL '24 hours'
AND status = 'pending'
`

func (q *Queries) CountConnectionRequestsToday(ctx context.Context, requesterID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countConnectionRequestsToday, requesterID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createConnectionRequest = `-- name: CreateConnectionRequest :one
INSERT INTO connections (
  requester_id,
  target_id,
  status
) VALUES (
  $1, $2, 'pending'
) RETURNING requester_id, target_id, status, created_at, updated_at
`

type CreateConnectionRequestParams struct {
	RequesterID uuid.UUID `json:"requester_id"`
	TargetID    uuid.UUID `json:"target_id"`
}

func (q *Queries) CreateConnectionRequest(ctx context.Context, arg CreateConnectionRequestParams) (Connection, error) {
	row := q.db.QueryRowContext(ctx, createConnectionRequest, arg.RequesterID, arg.TargetID)
	var i Connection
	err := row.Scan(
		&i.RequesterID,
		&i.TargetID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConnection = `-- name: GetConnection :one
SELECT requester_id, target_id, status, created_at, updated_at FROM connections
WHERE (requester_id = $1 AND target_id = $2)
   OR (requester_id = $2 AND target_id = $1)
LIMIT 1
`

type GetConnectionParams struct {
	RequesterID uuid.UUID `json:"requester_id"`
	TargetID    uuid.UUID `json:"target_id"`
}

func (q *Queries) GetConnection(ctx context.Context, arg GetConnectionParams) (Connection, error) {
	row := q.db.QueryRowContext(ctx, getConnection, arg.RequesterID, arg.TargetID)
	var i Connection
	err := row.Scan(
		&i.RequesterID,
		&i.TargetID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConnections = `-- name: ListConnections :many
SELECT 
    u.id, 
    u.username, 
    u.full_name, 
    u.avatar_url
FROM connections c
JOIN users u ON (u.id = c.requester_id OR u.id = c.target_id)
WHERE (c.requester_id = $1 OR c.target_id = $1)
  AND c.status = 'accepted'
  AND u.id != $1
`

type ListConnectionsRow struct {
	ID        uuid.UUID      `json:"id"`
	Username  string         `json:"username"`
	FullName  string         `json:"full_name"`
	AvatarUrl sql.NullString `json:"avatar_url"`
}

func (q *Queries) ListConnections(ctx context.Context, requesterID uuid.UUID) ([]ListConnectionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listConnections, requesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConnectionsRow
	for rows.Next() {
		var i ListConnectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FullName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConnectionStatus = `-- name: UpdateConnectionStatus :one
UPDATE connections
SET status = $3, updated_at = now()
WHERE requester_id = $1 AND target_id = $2
RETURNING requester_id, target_id, status, created_at, updated_at
`

type UpdateConnectionStatusParams struct {
	RequesterID uuid.UUID        `json:"requester_id"`
	TargetID    uuid.UUID        `json:"target_id"`
	Status      ConnectionStatus `json:"status"`
}

func (q *Queries) UpdateConnectionStatus(ctx context.Context, arg UpdateConnectionStatusParams) (Connection, error) {
	row := q.db.QueryRowContext(ctx, updateConnectionStatus, arg.RequesterID, arg.TargetID, arg.Status)
	var i Connection
	err := row.Scan(
		&i.RequesterID,
		&i.TargetID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
