// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: locations.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createLocation = `-- name: CreateLocation :one
INSERT INTO locations (
  user_id,
  geohash,
  geom,
  time_bucket,
  expires_at
) VALUES (
  $1, $2, ST_SetSRID(ST_MakePoint($3::float8, $4::float8), 4326), $5, $6
) RETURNING id, user_id, geohash, geom, time_bucket, created_at, expires_at
`

type CreateLocationParams struct {
	UserID     uuid.UUID `json:"user_id"`
	Geohash    string    `json:"geohash"`
	Lng        float64   `json:"lng"`
	Lat        float64   `json:"lat"`
	TimeBucket time.Time `json:"time_bucket"`
	ExpiresAt  time.Time `json:"expires_at"`
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error) {
	row := q.db.QueryRowContext(ctx, createLocation,
		arg.UserID,
		arg.Geohash,
		arg.Lng,
		arg.Lat,
		arg.TimeBucket,
		arg.ExpiresAt,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Geohash,
		&i.Geom,
		&i.TimeBucket,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredLocations = `-- name: DeleteExpiredLocations :exec
DELETE FROM locations
WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredLocations(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredLocations)
	return err
}
