// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	BanUser(ctx context.Context, arg BanUserParams) (User, error)
	BoostUser(ctx context.Context, arg BoostUserParams) (User, error)
	CountConnectionRequestsToday(ctx context.Context, requesterID uuid.UUID) (int64, error)
	CountCrossingsToday(ctx context.Context, userID1 uuid.UUID) (int64, error)
	CountStoryReactions(ctx context.Context, storyID uuid.UUID) (int64, error)
	CountStoryViews(ctx context.Context, storyID uuid.UUID) (int64, error)
	CountUnreadNotifications(ctx context.Context, userID uuid.UUID) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateConnectionRequest(ctx context.Context, arg CreateConnectionRequestParams) (Connection, error)
	CreateCrossing(ctx context.Context, arg CreateCrossingParams) (Crossing, error)
	CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreateReport(ctx context.Context, arg CreateReportParams) (Report, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateStory(ctx context.Context, arg CreateStoryParams) (Story, error)
	// Story Reactions
	CreateStoryReaction(ctx context.Context, arg CreateStoryReactionParams) (StoryReaction, error)
	// Story Views
	CreateStoryView(ctx context.Context, arg CreateStoryViewParams) (StoryView, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Used for panic mode - deletes all user data
	DeleteAllUserData(ctx context.Context, id uuid.UUID) error
	DeleteExpiredLocations(ctx context.Context) error
	DeleteExpiredStories(ctx context.Context) error
	// Delete messages older than specified days (default: 30 days)
	DeleteOldMessages(ctx context.Context) error
	// Delete notifications older than 30 days
	DeleteOldNotifications(ctx context.Context) error
	// Admin: Delete story
	DeleteStory(ctx context.Context, id uuid.UUID) error
	DeleteStoryReaction(ctx context.Context, arg DeleteStoryReactionParams) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	FindPotentialCrossings(ctx context.Context, arg FindPotentialCrossingsParams) ([]FindPotentialCrossingsRow, error)
	GetConnection(ctx context.Context, arg GetConnectionParams) (Connection, error)
	// Newest third
	// Get stories from connected users (not limited by radius)
	GetConnectionStories(ctx context.Context, userID uuid.UUID) ([]GetConnectionStoriesRow, error)
	GetConversionStats(ctx context.Context) (GetConversionStatsRow, error)
	GetCrossingsForUser(ctx context.Context, userID1 uuid.UUID) ([]Crossing, error)
	GetEngagementStats(ctx context.Context) (GetEngagementStatsRow, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	// Get stories within a bounding box for map view
	GetStoriesInBounds(ctx context.Context, arg GetStoriesInBoundsParams) ([]GetStoriesInBoundsRow, error)
	GetStoriesWithinRadius(ctx context.Context, arg GetStoriesWithinRadiusParams) ([]GetStoriesWithinRadiusRow, error)
	GetStoryByID(ctx context.Context, id uuid.UUID) (Story, error)
	GetStoryReactions(ctx context.Context, storyID uuid.UUID) ([]GetStoryReactionsRow, error)
	// Admin: Story stats
	GetStoryStats(ctx context.Context) (GetStoryStatsRow, error)
	// Only accessible by story owner
	GetStoryViewers(ctx context.Context, storyID uuid.UUID) ([]GetStoryViewersRow, error)
	GetStreakRetentionStats(ctx context.Context) (GetStreakRetentionStatsRow, error)
	// Get user's activity status and visibility
	GetUserActivityStatus(ctx context.Context, id uuid.UUID) (GetUserActivityStatusRow, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByPhone(ctx context.Context, phone string) (User, error)
	// Get public user profile information
	GetUserProfile(ctx context.Context, id uuid.UUID) (GetUserProfileRow, error)
	GetUserStats(ctx context.Context) (GetUserStatsRow, error)
	// Admin: List all stories
	ListAllStories(ctx context.Context, arg ListAllStoriesParams) ([]ListAllStoriesRow, error)
	ListConnections(ctx context.Context, requesterID uuid.UUID) ([]ListConnectionsRow, error)
	ListMessages(ctx context.Context, arg ListMessagesParams) ([]Message, error)
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error)
	// Admin: List all reports
	ListReports(ctx context.Context, arg ListReportsParams) ([]ListReportsRow, error)
	// Admin Queries
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	MarkAllNotificationsAsRead(ctx context.Context, userID uuid.UUID) error
	MarkNotificationAsRead(ctx context.Context, arg MarkNotificationAsReadParams) (Notification, error)
	// Admin: Resolve report
	ResolveReport(ctx context.Context, id uuid.UUID) (Report, error)
	// Privacy Features
	ToggleGhostMode(ctx context.Context, arg ToggleGhostModeParams) (User, error)
	UpdateConnectionStatus(ctx context.Context, arg UpdateConnectionStatusParams) (Connection, error)
	// Updates last_active_at and calculates activity streak
	UpdateUserActivity(ctx context.Context, id uuid.UUID) (User, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	UpdateUserTrust(ctx context.Context, arg UpdateUserTrustParams) (User, error)
}

var _ Querier = (*Queries)(nil)
